Bump surefire version to avoid build fail
Previous version caused build to fail with
java.lang.NoClassDefFoundError: java/sql/SQLException: java.sql.SQLException